export default {
  language: "English",
  proceed: "PROCEED",
  verify: "VERIFY",
  check: "CHECK",
  info:
    "Please login with your Phone no to continue:",
  otpInfo: "We've sent you a verification code on",
  wrongNumber: "Wrong Number?",
  namaste: "Namaste!",
  basicInfo: " We just needed some basic information to get started",
  userName: "Name",
  Gender: "Gender",
  Age: "Age",
  locationState: "location(state)",
  Male: "Male",
  Female: "Female",
  signup: "SIGNUP",
  live: "live",
  entertainment: "entertainment",
  feed: "feed",
  education: "education",
  news: "news",
  payments: "payments",
  finish: "finish",
  oneLastStep: "one last step",
  interestScreenHeaderMsg:
    "tell us about your interests to see the contents of your choice",
  addProfilePicDialogue: "add profile pic",
  home: "home",
  search: "search",
  activity: "activity",
  profile: "profile",
  games: "games",
  photo: "photo",
  video: "video",
  feelings: "feelings",
  checkIn: "check-in",
  tagFriends: "tag friends",
  vote: "vote",
  cancel: "cancel",
  post: "post",
  shareStatus: "share your status",
  comments: "comments",
  star: "star",
  reply: "reply",
  delete: "delete",
  showReplies: "showReplies",
  hideReplies: "hideReplies",
  jaiiho: "jaiiho",
  travel: "travel",
  busTickets: "Bus Tickets",
  trainTickets: "Train Tickets",
  upiAndBank: "UPI & BANK",
  upiTransfer: "upiTransfer",
  openBankAcc: "Open Bank Account",
  checkBalance: "check balance",
  mobilePrepaid: "mobile prepaid",
  mobilePostpaid: "mobile postpaid",
  dth: "DTH",
  electricity: "Electricty",
  landline: "Landline",
  gas: "gas",
  broadBand: "Broadband",
  water: "water",
  newsSource: "sources",
  minToRead: "min to read",
  status:"status",
  contactLists:"contact lists",
  followers: "Followers",
  stars: "Stars",
  popular: "Popular",
  friends: "Friends",
  following: "Following",
  posts: "Posts",
  artist: "Artist",
  creator: "Creator",
  smart: "Smart",
  gamer: "Gamer",
  modern: "Modern",
  list: "List",
  Grid: "grid",
  bookmarks: "Bookmarks",
  bookmark: "Bookmark",
  rechargeBillsHeader: "Mobile Recharge and Bill Pay",
  phoneNumber: "Enter Phone Number",
  prepaid: "Prepaid",
  postpaid: "Postpaid",
  selectOperator: "Select Operator",
  selectCircle: "Select Circle",
  amount: "Amount",
  proceedPayment: "Proceed",
  plans: "View Plans"
};
