export default {
  language: "ભાષા",
  proceed: "માં આગળ વધો",
  verify: "ચકાસો",
  check: "તપાસો",
  info:
    "અમે તમારા માટે શ્રેષ્ઠ પ્રયાસો પસંદ કરીએ છીએ, કૃપા કરીને ચકાસણી માટે તમારો મોબાઇલ નંબર દાખલ કરો",
  otpInfo: "અમે તમને એક ચકાસણી કોડ મોકલ્યો છે",
  wrongNumber: "ખોટો નંબર?",
  namaste: "નમસ્તે!",
  basicInfo: "અમને પ્રારંભ કરવા માટે ફક્ત થોડી મૂળભૂત માહિતીની જરૂર છે",
  userName: "નામ",
  Gender: "જાતિ",
  Age: "ઉંમર",
  locationState: "રાજ્ય",
  Male: "પુરુષ",
  Female: "સ્ત્રી",
  signup: "સાઇનઅપ",
  AndhraPradesh: "આંધ્રપ્રદેશ",
  ArunachalPradesh: "અરુણાચલ પ્રદેશ",
  Assam: "આસામ",
  Bihar: "બિહાર",
  Chhattisgarh: "છત્તીસગઢ",
  Goa: "ગોવા",
  Gujarat: "ગુજરાત",
  Haryana: "હરિયાણા",
  HimachalPradesh: "હિમાચલ પ્રદેશ",
  JammuKashmir: "જમ્મુ કાશ્મીર",
  Jharkhand: "ઝારખંડ",
  Karnataka: "કર્ણાટક",
  Kerala: "કેરળ",
  MadhyaPradesh: "મધ્યપ્રદેશ",
  Maharashtra: "મહારાષ્ટ્ર",
  Manipur: "મણિપુર",
  Meghalaya: "મેઘાલય",
  Mizoram: "મિઝોરમ",
  Nagaland: "નાગાલેન્ડ",
  Odisha: "ઓડિશા",
  Punjab: "પંજાબ",
  Rajasthan: "રાજસ્થાન",
  Sikkim: "સિક્કીમ",
  TamilNadu: "તમિલનાડુ",
  Telangana: "તેલંગણા",
  Tripura: "ત્રિપુરા",
  Uttarakhand: "ઉત્તરાખંડ",
  UttarPradesh: "ઉત્તરપ્રદેશ",
  WestBengal: "પશ્ચિમ બંગાળ",
  live: "લીવે",
  entertainment: "મનોરંજન",
  feed: "ફીડ",
  news: "સમાચાર",
  education: "શિક્ષણ",
  payments: "ચૂકવણી",
  finish: "સમાપ્ત",
  oneLastStep: "એક છેલ્લું પગલું!",
  interestScreenHeaderMsg:
    "আমাদের আপনার জন্য কন্টেন্ট curate আপনার আগ্রহ জানতে দিন",
  addProfilePicDialogue: "પ્રોફાઇલ ચિત્ર ઉમેરો",
  home: "ઘર",
  search: "શોધો",
  activity: "પ્રવૃત્તિ",
  profile: "પ્રોફાઇલ"
};
