export default {
  language: "भाषा",
  proceed: "हिंदी में आगे बढ़ें",
  verify: "वेरीफाई करें",
  check: "जाँच करें",
  info:
    "कृपया आगे बढ़ने के लिए अपने फ़ोन नंबर के साथ लॉगिन करें:",
  otpInfo: "हमने आपके फ़ोन नंबर पर एक कोड भेजा है",
  wrongNumber: "गलत नंबर?",
  namaste: "नमस्ते!",
  basicInfo: " हमें बस आरंभ करने के लिए कुछ बुनियादी जानकारी की आवश्यकता थी",
  userName: "नाम",
  Gender: "लिंग",
  Age: "आयु",
  locationState: "राज्य",
  AndhraPradesh: "आंध्र प्रदेश",
  ArunachalPradesh: "अरुणाचल प्रदेश",
  Assam: "असम",
  Bihar: "बिहार",
  Chhattisgarh: "छत्तीसगढ़",
  Goa: "गोवा",
  Gujarat: "गुजरात",
  Haryana: "हरयाणा",
  HimachalPradesh: "हिमाचल प्रदेश",
  JammuKashmir: "जम्मू और कश्मीर",
  Jharkhand: "झारखंड",
  Karnataka: "कर्नाटक",
  Kerala: "केरल",
  MadhyaPradesh: "मध्य प्रदेश",
  Maharashtra: "महाराष्ट्र",
  Manipur: "मणिपुर",
  Meghalaya: "मेघालय",
  Mizoram: "मिजोरम",
  Nagaland: "नगालैंड",
  Odisha: "ओडिशा",
  Punjab: "पंजाब",
  Rajasthan: "राजस्थान",
  Sikkim: "सिक्किम",
  TamilNadu: "तमिलनाडु",
  Telangana: "तेलंगाना",
  Tripura: "त्रिपुरा",
  Uttarakhand: "उत्तराखंड",
  UttarPradesh: "उत्तर प्रदेश",
  WestBengal: "पश्चिम बंगाल",
  Male: "पुरुष",
  Female: "महिला",
  signup: "साइन अप करें",
  live: "लाइव",
  entertainment: "मनोरंजन",
  feed: "फीड",
  news: "समाचार",
  payments: "लेन देन ",
  finish: "समाप्त",
  oneLastStep: "एक आखिरी कदम!",
  interestScreenHeaderMsg:
    "हमें सामग्री को क्यूरेट करने के लिए अपने हितों को बताएं तुम्हारे लिए",
  addProfilePicDialogue: "प्रोफ़ाइल फ़ोटो जोड़ें",
  home: "होम",
  search: "खोज",
  activity: "गतिविधि",
  profile: "प्रोफ़ाइल",
  games: "गेम्स",
  photo: "तस्वीर",
  video: "वीडियो",
  feelings: "भावना",
  checkIn: "चेक इन",
  tagFriends: "दोस्तों को टैग करें",
  vote: "वोट",
  cancel: "रद्द करना",
  post: "पोस्ट",
  shareStatus: "क्या चल रहा है?",
  comments: "कमैंट्स",
  star: "स्टार",
  reply: "रिप्लाई",
  delete: "डिलीट",
  showReplies: "जवाब दिखाओ",
  hideRepliesl: "जवाब छिपाएं",
  travel: "यात्रा",
  busTickets: "बस टिकट्",
  trainTickets: "ट्रैन टिकट्",
  upi:"यू पी आइ",
  upiNBank: "यू पी आइ और बैंक",
  rechargeHead: "रीचार्ज और बिल",
  openBankAC: "बैंक खाता",
  checkBalance: "बैलेन्स देखे",
  dth: "डीटीएच",
  electricity: "विद्युत",
  landline: "लैंड लाइन बिल",
  gas: "एलपीजी",
  water: "पानी",
  broadband: "इंटर्नेट",
  jaiiho: "जय हो!",
  back:"वापस",
  chats: "चाट्स",
  chatStatus: "स्टेटस",
  contactLists:"सम्पर्क सूची",
  followers: "फ़ालोअर्ज़",
  rechargeBillsHeader: "मोबाइल रीचार्ज और बिल भुगतान",
  phoneNumber: "फ़ोन नम्बर दर्ज़ कीजिए",
  prepaid: "प्रीपेड",
  postpaid: "पोस्टपेड",
  selectOperator: "ऑपरेटर चुनिए",
  selectCircle: "सर्कल चुनिए",
  amount: "रक़म",
  proceedPayment: "आगे बढ़ें",
  plans: "प्लाँस देखिए"
};
