export default {
  language: "ಭಾಷೆ",
  proceed: "ಕನ್ನಡದಲ್ಲಿ",
  verify: "ಪರಿಶೀಲಿಸು",
  check: "ಪರಿಶೀಲಿಸಿ",
  info:
    "ನಿಮಗಾಗಿ ಉತ್ತಮ ಅಭ್ಯಾಸಗಳನ್ನು ನಾವು ಆರಿಸಿಕೊಳ್ಳುತ್ತೇವೆ, ದಯವಿಟ್ಟು ಪರಿಶೀಲನೆಗಾಗಿ ನಿಮ್ಮ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ",
  otpInfo: "ನಾವು ನಿಮಗೆ ಪರಿಶೀಲನಾ ಕೋಡ್ ಕಳುಹಿಸಿದ್ದೇವೆ",
  wrongNumber: "ತಪ್ಪು ಸಂಖ್ಯೆ?",
  namaste: "ನಮಸ್ತೆ!",
  basicInfo: "ಪ್ರಾರಂಭಿಸಲು ನಾವು ಕೆಲವು ಮೂಲಭೂತ ಮಾಹಿತಿಯನ್ನು ಅಗತ್ಯವಿದೆ",
  userName: "ಹೆಸರು",
  Gender: "ಲಿಂಗ",
  Age: "ವಯಸ್ಸು",
  locationState: "ರಾಜ್ಯ",
  Male: "ಪುರುಷ",
  Female: "ಹೆಣ್ಣು",
  signup: "ಸೈನ್ ಅಪ್ ಮಾಡಿ",
  AndhraPradesh: "ಆಂಧ್ರ ಪ್ರದೇಶ",
  ArunachalPradesh: "ಅರುಣಾಚಲ ಪ್ರದೇಶ",
  Assam: "ಅಸ್ಸಾಂ",
  Bihar: "ಬಿಹಾರ",
  Chhattisgarh: "ಛತ್ತೀಸ್ಗಢ",
  Goa: "ಗೋವಾ",
  Gujarat: "ಗುಜರಾತ್",
  Haryana: "ಹರಿಯಾಣ",
  HimachalPradesh: "ಹಿಮಾಚಲ ಪ್ರದೇಶ",
  JammuKashmir: "ಜಮ್ಮು ಕಾಶ್ಮೀರ",
  Jharkhand: "ಜಾರ್ಖಂಡ್",
  Karnataka: "ಕರ್ನಾಟಕ",
  Kerala: "ಕೇರಳ",
  MadhyaPradesh: "ಮಧ್ಯ ಪ್ರದೇಶ",
  Maharashtra: "ಮಹಾರಾಷ್ಟ್ರ",
  Manipur: "ಮಣಿಪುರ",
  Meghalaya: "ಮೇಘಾಲಯ",
  Mizoram: "ಮಿಜೋರಾಮ್",
  Nagaland: "ನಾಗಾಲ್ಯಾಂಡ್",
  Odisha: "ಒಡಿಶಾ",
  Punjab: "ಪಂಜಾಬ್",
  Rajasthan: "ರಾಜಸ್ಥಾನ",
  Sikkim: "ಸಿಕ್ಕಿಂ",
  TamilNadu: "ತಮಿಳುನಾಡು",
  Telangana: "ತೆಲಂಗಾಣ",
  Tripura: "ತ್ರಿಪುರ",
  Uttarakhand: "ಉತ್ತರಾಖಂಡ್",
  UttarPradesh: "ಉತ್ತರ ಪ್ರದೇಶ",
  WestBengal: "ಪಶ್ಚಿಮ ಬಂಗಾಳ",
  live: "ಲೈವ್ ",
  entertainment: "ಮನರಂಜನೆ",
  feed: "ಫೀಡ್",
  news: "ಸುದ್ದಿ",
  education: "ಶಿಕ್ಷಣ",
  payments: "ಪಾವತಿಗಳು",
  finish: "ಮುಗಿಸಿ",
  oneLastStep: "ಒಂದು ಕೊನೆಯ ಹಂತ!",
  interestScreenHeaderMsg:
    "हमें सामग्री को क्यूरेट करने के लिए अपने हितों को बताएं तुम्हारे लिए",
  addProfilePicDialogue: "ಪ್ರೊಫೈಲ್ ಚಿತ್ರ ಸೇರಿಸಿ",
  home: "ಮನೆ",
  search: "ಹುಡುಕು",
  activity: "ಚಟುವಟಿಕೆ",
  profile: "ಪ್ರೊಫೈಲ್"
};
