export default {
  language: "भाषा",
  proceed: "मराठीमध्ये पुढे जा",
  verify: "सत्यापित करा",
  check: "तपासा",
  info:
    "आम्ही आपल्यासाठी सर्वोत्तम पद्धती निवडतो, कृपया सत्यापनासाठी आपला मोबाइल नंबर प्रविष्ट करा",
  otpInfo: "आम्ही आपल्याला कोड पाठवला आहे",
  wrongNumber: "चुकीचा क्रमांक?",
  namaste: "नमस्ते!",
  basicInfo: "आम्हाला प्रारंभ करण्यासाठी काही मूलभूत माहितीची आवश्यकता आहे",
  userName: "नाव",
  Gender: "लिंग",
  Age: "वय",
  locationState: "राज्य",
  Male: "पुरुष",
  Female: "मादी",
  signup: "साइन अप करा",
  AndhraPradesh: "आंध्र प्रदेश",
  ArunachalPradesh: "अरुणाचल प्रदेश",
  Assam: "आसाम",
  Bihar: "बिहार",
  Chhattisgarh: "छत्तीसगड",
  Goa: "गोवा",
  Gujarat: "गुजरात",
  Haryana: "हरियाणा",
  HimachalPradesh: "हिमाचल प्रदेश",
  JammuKashmir: "जम्मू कश्मीर",
  Jharkhand: "झारखंड",
  Karnataka: "कर्नाटक",
  Kerala: "केरळ",
  MadhyaPradesh: "मध्य प्रदेश",
  Maharashtra: "महाराष्ट्र",
  Manipur: "मणिपूर",
  Meghalaya: "मेघालय",
  Mizoram: "मिझोरम",
  Nagaland: "नागालँड",
  Odisha: "ओडिशा",
  Punjab: "पंजाब",
  Rajasthan: "राजस्थान",
  Sikkim: "सिक्किम",
  TamilNadu: "तमिळनाडु",
  Telangana: "तेलंगाना",
  Tripura: "त्रिपुरा",
  Uttarakhand: "उत्तराखंड",
  UttarPradesh: "उत्तर प्रदेश",
  WestBengal: "पश्चिम बंगाल",
  live: "लाइव्ह",
  entertainment: "मनोरंजन",
  feed: "फीड",
  news: "बातम्या",
  education: "शिक्षण",
  payments: "देयके",
  finish: "समाप्त",
  oneLastStep: "एक शेवटची पायरी!",
  interestScreenHeaderMsg:
    "हमें सामग्री को क्यूरेट करने के लिए अपने हितों को बताएं तुम्हारे लिए",
  addProfilePicDialogue: "प्रोफाइल चित्र जोडा",
  home: "घर",
  search: "शोध",
  activity: "क्रियाकलाप",
  profile: "प्रोफाइल"
};
