export default {
  language: "ଭାଷା",
  proceed: "ଆଗକୁ ବଢ଼ନ୍ତୁ",
  verify: "ଯାଞ୍ଚ୍ କରନ୍ତୁ",
  check: "ଚେକ କରନ୍ତୁ",
  info: "ଦୟାକରି ଫୋନ ନମ୍ବର ଏଣ୍ଟର କରନ୍ତୁ ",
  otpInfo: "ଆମେ ଆପଣଙ୍କ ଫୋନ କୁ ଗୋଟିଏ କୋଡ଼ ପଠେଇଛୁ",
  wrongNumber: "ଭୁଲ ନମ୍ବର?",
  namaste: "ନମସ୍ତେ!",
  basicInfo: " ଦୟାକରି ଆପଣଙ୍କ ପ୍ରକୃତ ତଥ୍ୟ ଏଣ୍ଟର କରନ୍ତୁ",
  userName: "ନାମ",
  Gender: "ଲିଙ୍ଗ",
  Age: "ବୟସ",
  locationState: "ରାଜ୍ୟ",
  Male: "ପୁରୁଷ",
  Female: "ମହିଳା",
  signup: "ସାଇନ୍ ଅପ୍ କରନ୍ତୁ",
  AndhraPradesh: "ଆନ୍ଧ୍ରପ୍ରଦେଶ",
  ArunachalPradesh: "ଅରୁଣାଂଚଳପ୍ରଦେଶ",
  Assam: "ଆସାମ",
  Bihar: "ବିହାର",
  Chhattisgarh: "ଛତିଶଗଡ",
  Goa: "ଗୋଆ",
  Gujarat: "ଗୁଜରାଟ",
  Haryana: "ହରିଆଣା ",
  HimachalPradesh: "ହିମାଚଳପ୍ରଦେଶ",
  JammuKashmir: "ଜମ୍ମୁକାଶ୍ମୀର",
  Jharkhand: "ଝାରଖଣ୍ଡ",
  Karnataka: "କର୍ଣ୍ଣାଟକ",
  Kerala: "କେରଳ",
  MadhyaPradesh: "ମଧ୍ୟପ୍ରଦେଶ",
  Maharashtra: "ମହାରାଷ୍ଟ୍ର",
  Manipur: "ମଣିପୁର",
  Meghalaya: "ମେଘାଳୟ",
  Mizoram: "ମିଜୋରାମ",
  Nagaland: "ନାଗାଲାଣ୍ଡ",
  Odisha: "ଓଡିଶା",
  Punjab: "ପଂଜାବ",
  Rajasthan: "ରାଜସ୍ଥାନ",
  Sikkim: "ଶିକ୍କିମ",
  TamilNadu: "ତାମିଲନାଡୁ",
  Telangana: "ତେଲେଙ୍ଗାନା",
  Tripura: "ତ୍ରିପୁରା",
  Uttarakhand: "ଉତ୍ତରାଖଣ୍ଡ",
  UttarPradesh: "ଉତ୍ତର ପ୍ରଦେଶ",
  WestBengal: "ପଶ୍ଚିମ ବଙ୍ଗ",
  live: "ଲାଇଭ",
  entertainment: "ମନୋରଞ୍ଜନ",
  feed: "ଫିଡ଼",
  news: "ସମ୍ବାଦ",
  education: "ଶିକ୍ଷ୍ୟା",
  payments: "ପେମେଂଟ ",
  finish: "ଅନ୍ତ",
  oneLastStep: "ଏକ ଅନ୍ତିମ ପଦକ୍ଷେପ!",
  interestScreenHeaderMsg:
    "हमें सामग्री को क्यूरेट करने के लिए अपने हितों को बताएं तुम्हारे लिए",
  addProfilePicDialogue: "ప్రొఫైల్ చిత్రాన్ని జోడించండి",
  home: "ହୋମ",
  search: "ସେଅର୍ଚ୍ଚ",
  activity: "କ୍ରିୟା",
  profile: "ପ୍ରୋଫାଇଲ",
  games: "ଗମେସ",
  photo: "ଫୋଟୋ",
  video: "ଭିଡ଼ିଓ",
  feelings: "ଫିଇଲିନଗସ",
  checkIn: "ଚେକକିନ",
  tagFriends: "tag friends",
  vote: "ଭୋଟ",
  cancel: "କ୍ୟାନ୍ସଲା",
  post: "ପୋଷ୍ଟ",
  shareStatus: "ସ୍ଟାଟସ",
  comments: "କମେଣ୍ଟସ",
  star: "ଷ୍ଟାର",
  reply: "ରପଆଲାଏ",
  delete: "ଡିଲିଟ",
  showReplies: "showReplies",
  hideReplies: "hideReplies",
  jaiiho:"ଜୟ ହୋ"
};
