export default {
  language: "மொழி",
  proceed: "தமிழ் தொடரவும்",
  verify: "சரிபார்க்க",
  check: "சரிபார்க்கவும்",
  info:
    "நாங்கள் உங்களுக்கு சிறந்த நடைமுறைகளைத் தேர்ந்தெடுத்துள்ளோம், தயவுசெய்து உங்கள் மொபைல் எண்ணை சரிபார்ப்பிற்காக உள்ளிடவும்",
  otpInfo: "உங்களுக்கு ஒரு குறியீடு அனுப்பியுள்ளோம்",
  wrongNumber: "தவறான எண்?",
  namaste: "நமஸ்தே!",
  basicInfo: " ஆரம்பிக்க சில அடிப்படை தகவல்கள் தேவை",
  userName: "பெயர்",
  Gender: "பாலினம்",
  Age: "வயது",
  locationState: "நிலை",
  Male: "ஆண்",
  Female: "பெண்",
  signup: "இணைந்ததற்கு",
  AndhraPradesh: "ஆந்திரப் பிரதேசம்",
  ArunachalPradesh: "அருணாச்சல பிரதேசம்",
  Assam: "அசாம்",
  Bihar: "பீகார்",
  Chhattisgarh: "சத்தீஸ்கர்",
  Goa: "கோவா",
  Gujarat: "குஜராத்",
  Haryana: "அரியானா",
  HimachalPradesh: "ஹிமாச்சல பிரதேசம்",
  JammuKashmir: "ஜம்மு காஷ்மீர்",
  Jharkhand: "ஜார்கண்ட்",
  Karnataka: "கர்நாடக",
  Kerala: "கேரளா",
  MadhyaPradesh: "மத்தியப் பிரதேசம்",
  Maharashtra: "மகாராஷ்டிரா",
  Manipur: "மணிப்பூர்",
  Meghalaya: "மேகாலயா",
  Mizoram: "மிசோரம்",
  Nagaland: "நாகாலாந்து",
  Odisha: "ஒடிசா",
  Punjab: "பஞ்சாப்",
  Rajasthan: "ராஜஸ்தான்",
  Sikkim: "சிக்கிம்",
  TamilNadu: "தமிழ்நாடு",
  Telangana: "தெலுங்கானா",
  Tripura: "திரிபுரா",
  Uttarakhand: "உத்தரகண்ட்",
  UttarPradesh: "உத்தரப் பிரதேசம்",
  WestBengal: "மேற்கு வங்கம்",
  live: "ଲାଇଭ",
  entertainment: "பொழுதுபோக்கு",
  feed: "ଫିଡ଼",
  news: "செய்தி",
  education: "கல்வி",
  payments: "பணம்",
  finish: "பூச்சு",
  oneLastStep: "ஒரு கடைசி படி!",
  interestScreenHeaderMsg:
    "हमें सामग्री को क्यूरेट करने के लिए अपने हितों को बताएं तुम्हारे लिए",
  addProfilePicDialogue: "சுயவிவரத்தைச் சேர்க்கவும்",
  home: "வீட்டில்",
  search: "தேடல்",
  activity: "நடவடிக்கை",
  profile: "சுயவிவர"
};
