export default {
  language: "భాష",
  proceed: "ముందుకు",
  verify: "ధ్రువీకరించడం",
  check: "తనిఖీ",
  info:
    "మేము మీ కోసం ఉత్తమ పద్ధతులను ఎంచుకుంటాము, ధృవీకరణ కోసం దయచేసి మీ మొబైల్ నంబర్ను నమోదు చేయండి",
  otpInfo: "మేము మీకు కోడ్ను పంపాము",
  wrongNumber: "తప్పు సంఖ్య?",
  namaste: "నమస్తే!",
  basicInfo: "ప్రారంభించడానికి కొన్ని ప్రాథమిక సమాచారం మాకు అవసరం",
  userName: "పేరు",
  Gender: "లింగ",
  Age: "వయస్సు",
  locationState: "రాష్ట్ర",
  Male: "పురుషుడు",
  Female: "మహిళ",
  signup: "చేరడం",
  AndhraPradesh: "ఆంధ్రప్రదేశ్",
  ArunachalPradesh: "అరుణాచల్ ప్రదేశ్",
  Assam: "అస్సాం",
  Bihar: "బీహార్",
  Chhattisgarh: "છત્તીસગઢ",
  Goa: "ગોવા",
  Gujarat: "గుజరాత్",
  Haryana: "హర్యానా",
  HimachalPradesh: "హిమాచల్ ప్రదేశ్",
  JammuKashmir: "జమ్మూ కాశ్మీర్",
  Jharkhand: "జార్ఖండ్",
  Karnataka: "కర్ణాటక",
  Kerala: "కేరళ",
  MadhyaPradesh: "మధ్యప్రదేశ్",
  Maharashtra: "మహారాష్ట్ర",
  Manipur: "మణిపూర్",
  Meghalaya: "మేఘాలయ",
  Mizoram: "మిజోరం",
  Nagaland: "నాగాలాండ్",
  Odisha: "ఒడిషా",
  Punjab: "పంజాబ్",
  Rajasthan: "రాజస్థాన్",
  Sikkim: "సిక్కిం",
  TamilNadu: "తమిళనాడు",
  Telangana: "తెలంగాణ",
  Tripura: "త్రిపుర",
  Uttarakhand: "ఉత్తరాఖండ్",
  UttarPradesh: "ఉత్తరప్రదేశ్",
  WestBengal: "పశ్చిమబెంగాల్",
  live: "లైవ్",
  entertainment: "వినోదం",
  feed: "ఫీడ్",
  news: "వార్తలు",
  education: "చదువు",
  payments: "చెల్లింపులు",
  finish: "ముగింపు",
  oneLastStep: "చివరి దశ!",
  interestScreenHeaderMsg:
    "हमें सामग्री को क्यूरेट करने के लिए अपने हितों को बताएं तुम्हारे लिए",
  addProfilePicDialogue: "ప్రొఫైల్ చిత్రాన్ని జోడించండి",
  home: "హోమ్",
  search: "శోధన",
  activity: "కార్యకలాపాలు",
  profile: "ప్రొఫైల్",
  games:"ఆటలు"
};
